### ISSUE TITLE
Error executing build start: ad-hoc

### ISSUE THREAD

**Issue by AndresArias09** [Appollo-CLI/Appollo#43] opened 2023-08-28 16:54 UTC
Hi, 

Today I tried to execute build start: ad-hoc command for my flutter app, but im having the following error:

```bash
PS K:\cardiosuite\CardioSuiteMovil> py -m appollo build start
 Build type ad-hoc
Zipping K:\cardiosuite\CardioSuiteMovil
Uploading K:\cardiosuite\CardioSuiteMovil (3.76 MB)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\leona\AppData\Local\Programs\Python\Python311\Lib\site-packages\appollo\__main__.py", line 67, in <module>
    appollo()
  File "C:\Users\leona\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\leona\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\leona\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\leona\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\leona\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\leona\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\leona\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\leona\AppData\Local\Programs\Python\Python311\Lib\site-packages\appollo\helpers.py", line 57, in run
    return ctx.invoke(f, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\leona\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\leona\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\leona\AppData\Local\Programs\Python\Python311\Lib\site-packages\appollo\commands\build.py", line 532, in start
    build_instance = api.post(
                     ^^^^^^^^^
  File "C:\Users\leona\AppData\Local\Programs\Python\Python311\Lib\site-packages\appollo\api.py", line 93, in post
    return _request("post", route, params=params, data=json_data, files=files, authorization=authorization, auth_data=auth_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\leona\AppData\Local\Programs\Python\Python311\Lib\site-packages\appollo\api.py", line 59, in _request
    print_validation_error(console, error)
  File "C:\Users\leona\AppData\Local\Programs\Python\Python311\Lib\site-packages\appollo\helpers.py", line 24, in print_validation_error
    console.print(f"Error: {error}")
  File "C:\Users\leona\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\console.py", line 1590, in print
    renderables = self._collect_renderables(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\leona\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\console.py", line 1454, in _collect_renderables
    self.render_str(
  File "C:\Users\leona\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\console.py", line 1346, in render_str
    rich_text = render_markup(
                ^^^^^^^^^^^^^^
  File "C:\Users\leona\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\markup.py", line 159, in render
    raise MarkupError(
rich.errors.MarkupError: closing tag '[/v1/devices?limit=200]' at position 45 doesn't match any open tag
```

I tried to execute appollo build logs command, but appollo shows me logs from app build from 5 months ago o more.

![image](https://github.com/Appollo-CLI/Appollo/assets/30777930/0efb3ef8-a223-4e2b-af49-860c61976f5b)

Any ideas of this error?

My python version is 3.11.4

**Comment by tchavetdeuse** [comment] 2023-08-29 07:53
Duplicate of #38 
Please update your Appollo version and ensure you have accepted the latest Apple user agreement.

**Closed by tchavetdeuse** 2023-08-29 07:53 UTC
